#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MODE="${1:---all}"

if [ ! -f ".env" ]; then
  cat > .env <<'EOF'
# Generated by scripts/demo-workflow.sh
EOF
fi

set -a
source .env
set +a

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "[demo] ERROR: missing required command '$1'" >&2
    exit 1
  fi
}

for cmd in forge cast jq awk sed grep; do
  require_cmd "$cmd"
done

log() {
  printf "\n[demo] %s\n" "$1"
}

explorer_base_for_chain() {
  case "$1" in
    1301) echo "https://sepolia.uniscan.xyz/tx/" ;;
    84532) echo "https://sepolia.basescan.org/tx/" ;;
    11155420) echo "https://sepolia-optimism.etherscan.io/tx/" ;;
    421614) echo "https://sepolia.arbiscan.io/tx/" ;;
    137) echo "https://polygonscan.com/tx/" ;;
    *) echo "" ;;
  esac
}

upsert_env() {
  local key="$1"
  local value="$2"
  local tmp_file
  tmp_file="$(mktemp)"

  awk -v k="$key" -v v="$value" '
    BEGIN { done = 0 }
    $0 ~ ("^" k "=") { print k "=" v; done = 1; next }
    { print }
    END { if (!done) print k "=" v }
  ' .env > "$tmp_file"

  mv "$tmp_file" .env
  export "$key=$value"
}

print_tx_links_from_runfile() {
  local run_file="$1"
  local chain_id="$2"
  local explorer_base
  explorer_base="$(explorer_base_for_chain "$chain_id")"

  if [ ! -f "$run_file" ]; then
    echo "[demo] WARN: run file not found: $run_file"
    return 0
  fi

  echo "[demo] Transactions from $(basename "$run_file"):"
  jq -r '.transactions[] | [.hash // "", .contractName // "-", .transactionType // "-", .contractAddress // "-"] | @tsv' "$run_file" \
    | while IFS=$'\t' read -r tx_hash contract_name tx_type contract_address; do
      [ -z "$tx_hash" ] && continue
      if [ -n "$explorer_base" ]; then
        echo "  - ${tx_type} ${contract_name} ${tx_hash}"
        echo "    ${explorer_base}${tx_hash}"
      else
        echo "  - ${tx_type} ${contract_name} ${tx_hash}"
      fi
      if [ "$contract_address" != "-" ]; then
        echo "    deployed: ${contract_address}"
      fi
    done
}

print_user_journey() {
  cat <<'EOF'
[demo] User-perspective flow:
  1. Integrator points frontend at existing REGISTRY + HOOK_ADDRESS.
  2. Admin selects profile (Base / Optimism / Arbitrum) and applies policy.
  3. Trader submits swap intent via router into the hooked pool.
  4. Hook calls registry policy engine and emits deterministic allow/block reason codes.
  5. Team validates outcomes with tx traces, events, and test proofs.
EOF
}

print_proof_inventory() {
  cat <<'EOF'
[demo] Proof inventory:
  - Core hook: src/ChainLocalizedRoutingHook.sol
  - Policy engine: src/RoutingPolicyRegistry.sol
  - Policy types: src/libraries/PolicyTypes.sol
  - Integration lifecycle proof: test/integration/ProfileLifecycle.t.sol
  - Hook behavior proof: test/ChainLocalizedRoutingHook.t.sol
  - Registry edge/fuzz/invariant proofs:
    test/RoutingPolicyRegistry.t.sol
    test/fuzz/RoutingPolicyRegistryFuzz.t.sol
    test/invariant/RoutingPolicyRegistryInvariant.t.sol
EOF
}

run_local_proof() {
  log "PHASE 1/6 (User Perspective): end-to-end local proof plan"
  print_user_journey
  print_proof_inventory

  scripts/bootstrap.sh

  log "PHASE 2/6: profile lifecycle integration proof"
  forge test --match-test testProfileSpecificOutcomes -vvv

  log "PHASE 3/6: hook-level allow/block behavior proof"
  forge test --match-contract ChainLocalizedRoutingHookTest -vv

  log "PHASE 4/6: policy engine edge behavior proof"
  forge test --match-contract RoutingPolicyRegistryTest -vv

  log "PHASE 5/6: policy fuzz + invariant proof"
  forge test --match-contract RoutingPolicyRegistryFuzzTest -vv
  forge test --match-contract RoutingPolicyRegistryInvariantTest -vv

  log "PHASE 6/6: local workflow complete"
}

resolve_testnet_env() {
  if [ -z "${RPC_URL:-}" ] && [ -n "${SEPOLIA_RPC_URL:-}" ]; then
    upsert_env "RPC_URL" "$SEPOLIA_RPC_URL"
  fi
  if [ -z "${PRIVATE_KEY:-}" ] && [ -n "${SEPOLIA_PRIVATE_KEY:-}" ]; then
    upsert_env "PRIVATE_KEY" "$SEPOLIA_PRIVATE_KEY"
  fi

  if [ -z "${RPC_URL:-}" ]; then
    echo "[demo] ERROR: RPC_URL is required for testnet demo." >&2
    exit 1
  fi
  if [ -z "${PRIVATE_KEY:-}" ] && [ -z "${ACCOUNT:-}" ]; then
    echo "[demo] ERROR: PRIVATE_KEY or ACCOUNT is required for testnet demo." >&2
    exit 1
  fi

  local chain_id
  chain_id="$(cast chain-id --rpc-url "$RPC_URL")"
  upsert_env "CHAIN_ID" "$chain_id"

  if [ -z "${OWNER_ADDRESS:-}" ] && [ -n "${PRIVATE_KEY:-}" ]; then
    upsert_env "OWNER_ADDRESS" "$(cast wallet address --private-key "$PRIVATE_KEY")"
  fi

  # BaseScript constructor requires TOKEN0/TOKEN1 env values even when the script path does not consume them.
  if [ -z "${TOKEN0:-}" ]; then
    upsert_env "TOKEN0" "0x0000000000000000000000000000000000000001"
  fi
  if [ -z "${TOKEN1:-}" ]; then
    upsert_env "TOKEN1" "0x0000000000000000000000000000000000000002"
  fi
}

run_forge_script_broadcast() {
  local target="$1"
  if [ -n "${PRIVATE_KEY:-}" ]; then
    forge script "$target" --rpc-url "$RPC_URL" --private-key "$PRIVATE_KEY" --broadcast
  else
    if [ -z "${ACCOUNT:-}" ] || [ -z "${SENDER:-}" ]; then
      echo "[demo] ERROR: using ACCOUNT requires SENDER." >&2
      exit 1
    fi
    forge script "$target" --rpc-url "$RPC_URL" --account "$ACCOUNT" --sender "$SENDER" --broadcast
  fi
}

address_has_code() {
  local addr="$1"
  local code
  code="$(cast code "$addr" --rpc-url "$RPC_URL" 2>/dev/null || true)"
  [ -n "$code" ] && [ "$code" != "0x" ]
}

ensure_testnet_deployed() {
  local chain_id="$CHAIN_ID"

  if [ -z "${REGISTRY:-}" ] || [ -z "${HOOK_ADDRESS:-}" ]; then
    echo "[demo] ERROR: REGISTRY and HOOK_ADDRESS must already exist in .env for testnet proof." >&2
    exit 1
  fi
  if ! address_has_code "$REGISTRY"; then
    echo "[demo] ERROR: REGISTRY has no bytecode on chain ${chain_id}: ${REGISTRY}" >&2
    exit 1
  fi
  if ! address_has_code "$HOOK_ADDRESS"; then
    echo "[demo] ERROR: HOOK_ADDRESS has no bytecode on chain ${chain_id}: ${HOOK_ADDRESS}" >&2
    exit 1
  fi

  log "PHASE 2/6 (Testnet): reusing deployed contracts from .env (no deployments)"
  echo "[demo] REGISTRY=${REGISTRY}"
  echo "[demo] HOOK_ADDRESS=${HOOK_ADDRESS}"

  local run_file="broadcast/00_DeployHook.s.sol/${chain_id}/run-latest.json"
  if [ -f "$run_file" ]; then
    echo "[demo] Existing deployment transactions:"
    print_tx_links_from_runfile "$run_file" "$chain_id"
  else
    echo "[demo] WARN: no local deployment run file found at ${run_file}; continuing with existing addresses."
  fi
}

ensure_demo_pool_id() {
  if [ -z "${POOL_ID:-}" ]; then
    upsert_env "POOL_ID" "$(cast keccak "chain-localized-routing-hook:demo:pool:${CHAIN_ID}")"
  fi
}

configure_policy_profile() {
  local profile_name="$1"
  local profile_id="$2"
  local max_amount_in="$3"
  local max_price_impact_bps="$4"
  local cooldown_seconds="$5"
  local max_swaps_per_block="$6"
  local allowlist="$7"
  local dynamic_fee="$8"
  local base_fee="$9"
  local gas_ceiling_wei="${10}"

  log "PHASE 3/6 (Testnet): configure ${profile_name} policy for POOL_ID=${POOL_ID}"
  echo "[demo] ${profile_name} expectation:"
  if [ "$profile_name" = "BASE" ]; then
    echo "  - higher throughput / looser limits"
  elif [ "$profile_name" = "OPTIMISM" ]; then
    echo "  - stricter limits / anti-MEV style throttling"
  elif [ "$profile_name" = "ARBITRUM" ]; then
    echo "  - allowlist-oriented mode with dynamic-fee support"
  fi

  CHAIN_ID="$CHAIN_ID" \
  REGISTRY="$REGISTRY" \
  POOL_ID="$POOL_ID" \
  PROFILE_ID="$profile_id" \
  POLICY_ENABLED=true \
  MAX_AMOUNT_IN="$max_amount_in" \
  MAX_PRICE_IMPACT_BPS="$max_price_impact_bps" \
  COOLDOWN_SECONDS="$cooldown_seconds" \
  MAX_SWAPS_PER_BLOCK="$max_swaps_per_block" \
  ENFORCE_ROUTER_ALLOWLIST="$allowlist" \
  ENFORCE_ACTOR_DENYLIST=false \
  DYNAMIC_FEE_ENABLED="$dynamic_fee" \
  BASE_FEE="$base_fee" \
  GAS_PRICE_CEILING_WEI="$gas_ceiling_wei" \
  run_forge_script_broadcast "script/11_SetProfilePolicy.s.sol:SetProfilePolicyScript"

  local run_file="broadcast/11_SetProfilePolicy.s.sol/${CHAIN_ID}/run-latest.json"
  print_tx_links_from_runfile "$run_file" "$CHAIN_ID"

  local active_profile policy_snapshot
  active_profile="$(cast call "$REGISTRY" "getChainProfile(uint256)(uint8)" "$CHAIN_ID" --rpc-url "$RPC_URL" 2>/dev/null || true)"
  policy_snapshot="$(cast call "$REGISTRY" "getPoolPolicy(uint256,bytes32)((bool,uint128,uint24,uint32,uint16,bool,bool,bool,uint24,uint64))" "$CHAIN_ID" "$POOL_ID" --rpc-url "$RPC_URL" 2>/dev/null || true)"
  echo "[demo] onchain profile enum value: ${active_profile:-unavailable}"
  echo "[demo] onchain policy snapshot: ${policy_snapshot:-unavailable}"
}

send_cast_tx() {
  local signature="$1"
  shift
  local tx_hash
  tx_hash="$(cast send --async "$REGISTRY" "$signature" "$@" --rpc-url "$RPC_URL" --private-key "$PRIVATE_KEY")"
  local explorer
  explorer="$(explorer_base_for_chain "$CHAIN_ID")"
  echo "[demo] tx: ${tx_hash}"
  if [ -n "$explorer" ]; then
    echo "[demo] url: ${explorer}${tx_hash}"
  fi
}

run_allowlist_denylist_demo() {
  if [ -z "${PRIVATE_KEY:-}" ] || [ -z "${OWNER_ADDRESS:-}" ]; then
    echo "[demo] WARN: skipping allowlist/denylist tx demo (PRIVATE_KEY and OWNER_ADDRESS required)."
    return 0
  fi

  log "PHASE 4/6 (Testnet): allowlist + denylist admin actions"
  send_cast_tx "setRouterAllowlist(uint256,bytes32,address,bool)" "$CHAIN_ID" "$POOL_ID" "$OWNER_ADDRESS" true
  send_cast_tx "setActorDenylist(uint256,bytes32,address,bool)" "$CHAIN_ID" "$POOL_ID" "$OWNER_ADDRESS" true
  send_cast_tx "setActorDenylist(uint256,bytes32,address,bool)" "$CHAIN_ID" "$POOL_ID" "$OWNER_ADDRESS" false
}

run_testnet_proof() {
  log "PHASE 1/6 (Testnet): resolve environment and network context"
  resolve_testnet_env
  scripts/bootstrap.sh

  echo "[demo] chainId=${CHAIN_ID}"
  echo "[demo] rpc=${RPC_URL}"
  print_user_journey

  ensure_testnet_deployed
  ensure_demo_pool_id
  echo "[demo] POOL_ID=${POOL_ID}"

  configure_policy_profile "BASE" 1 "2000000000000000000" "2500" "0" "25" "false" "false" "2500" "5000000000"
  configure_policy_profile "OPTIMISM" 2 "500000000000000000" "800" "2" "8" "false" "true" "3000" "2000000000"
  configure_policy_profile "ARBITRUM" 3 "1000000000000000000" "1500" "1" "12" "true" "true" "3500" "1000000000"

  run_allowlist_denylist_demo

  log "PHASE 5/6 (Testnet): frontend user flow checkpoints"
  cat <<'EOF'
[demo] Frontend user checkpoints:
  - Connect wallet on target chain
  - Paste REGISTRY and POOL_ID from .env
  - Select Base/Optimism/Arbitrum profile and apply policy
  - Toggle allowlist/denylist and observe on-chain event/log updates
  - Run profile lifecycle locally to prove expected allow/block outcomes
EOF

  log "PHASE 6/6 (Testnet): complete"
}

run_multichain_proof() {
  local deployments_file="shared/constants/deployments.multichain.json"

  log "PHASE 1/3 (Multi-chain): load existing multi-chain deployment registry (no deployments)"

  if [ ! -f "$deployments_file" ]; then
    echo "[demo] WARN: deployment summary file not found: $deployments_file"
    return 0
  fi

  log "PHASE 2/3 (Multi-chain): deployment summary and tx links"
  jq -c '
    to_entries[]
    | select(.key != "updatedAt")
    | {
        key: .key,
        chainId: (.value.chainId // ""),
        registry: (.value.registry // ""),
        hook: (.value.hook // ""),
        skipped: (.value.skipped // false),
        reason: (.value.reason // "")
      }
  ' "$deployments_file" | while IFS= read -r row; do
    local key chain_id registry hook skipped reason
    key="$(jq -r '.key' <<< "$row")"
    chain_id="$(jq -r '.chainId' <<< "$row")"
    registry="$(jq -r '.registry' <<< "$row")"
    hook="$(jq -r '.hook' <<< "$row")"
    skipped="$(jq -r '.skipped' <<< "$row")"
    reason="$(jq -r '.reason' <<< "$row")"

    if [ "$skipped" = "true" ]; then
      echo "[demo] ${key}: skipped (${reason})"
      continue
    fi

    if [ -z "$registry" ] || [ -z "$hook" ] || [ -z "$chain_id" ]; then
      echo "[demo] ${key}: not deployed"
      continue
    fi

    echo "[demo] ${key}:"
    echo "  chainId: ${chain_id}"
    echo "  registry: ${registry}"
    echo "  hook: ${hook}"
    print_tx_links_from_runfile "broadcast/00_DeployHook.s.sol/${chain_id}/run-latest.json" "$chain_id"
  done

  log "PHASE 3/3 (Multi-chain): complete"
}

case "$MODE" in
  --multi-chain)
    run_multichain_proof
    ;;
  --local)
    run_local_proof
    ;;
  --testnet)
    run_testnet_proof
    ;;
  --profiles)
    run_local_proof
    if [ -n "${RPC_URL:-}" ]; then
      run_testnet_proof
    else
      echo "[demo] WARN: RPC_URL not set; skipped testnet profile configuration."
    fi
    ;;
  --all)
    run_local_proof
    if [ -n "${RPC_URL:-}" ]; then
      run_testnet_proof
    else
      echo "[demo] WARN: RPC_URL not set; skipped testnet phase."
    fi
    ;;
  *)
    echo "Usage: $0 [--multi-chain|--local|--testnet|--profiles|--all]" >&2
    exit 1
    ;;
esac
