#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

DEPLOYMENTS_FILE="shared/constants/deployments.multichain.json"

if [ ! -f ".env" ]; then
  cat > .env <<'EOF'
# Generated by scripts/deploy-multichain.sh
EOF
fi

set -a
source .env
set +a

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "[multichain] ERROR: missing required command '$1'" >&2
    exit 1
  fi
}

for cmd in forge cast jq awk sed grep; do
  require_cmd "$cmd"
done

if [ -z "${PRIVATE_KEY:-}" ] && [ -z "${ACCOUNT:-}" ]; then
  echo "[multichain] ERROR: set PRIVATE_KEY (recommended) or ACCOUNT+SENDER in .env" >&2
  exit 1
fi

upsert_env() {
  local key="$1"
  local value="$2"
  local tmp_file
  tmp_file="$(mktemp)"

  awk -v k="$key" -v v="$value" '
    BEGIN { done = 0 }
    $0 ~ ("^" k "=") { print k "=" v; done = 1; next }
    { print }
    END { if (!done) print k "=" v }
  ' .env > "$tmp_file"

  mv "$tmp_file" .env
  export "$key=$value"
}

run_forge_script_broadcast() {
  local target="$1"
  local rpc_url="$2"
  if [ -n "${PRIVATE_KEY:-}" ]; then
    forge script "$target" --rpc-url "$rpc_url" --private-key "$PRIVATE_KEY" --broadcast
  else
    if [ -z "${ACCOUNT:-}" ] || [ -z "${SENDER:-}" ]; then
      echo "[multichain] ERROR: ACCOUNT mode requires SENDER." >&2
      exit 1
    fi
    forge script "$target" --rpc-url "$rpc_url" --account "$ACCOUNT" --sender "$SENDER" --broadcast
  fi
}

address_has_code() {
  local addr="$1"
  local rpc_url="$2"
  local code
  local attempt

  for attempt in 1 2 3; do
    if code="$(cast code "$addr" --rpc-url "$rpc_url" 2>/dev/null)"; then
      [ -n "$code" ] && [ "$code" != "0x" ]
      return $?
    fi
    sleep 1
  done

  return 2
}

is_truthy() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

sanitize_rpc_url() {
  local rpc_url="$1"
  # Keep only scheme + host to avoid persisting provider API keys/tokens.
  echo "$rpc_url" | sed -E 's#(https?://[^/]+).*#\1#'
}

ensure_deployments_file() {
  if [ ! -f "$DEPLOYMENTS_FILE" ]; then
    mkdir -p "$(dirname "$DEPLOYMENTS_FILE")"
    cat > "$DEPLOYMENTS_FILE" <<'EOF'
{
  "updatedAt": null,
  "baseSepolia": null,
  "optimismSepolia": null,
  "arbitrumSepolia": null,
  "polygon": null
}
EOF
  fi
}

update_deployments_file() {
  local key="$1"
  local chain_id="$2"
  local registry="$3"
  local hook="$4"
  local rpc_url="$5"
  local deployer="$6"
  local sanitized_rpc_url
  local tmp_file
  tmp_file="$(mktemp)"
  sanitized_rpc_url="$(sanitize_rpc_url "$rpc_url")"

  jq \
    --arg key "$key" \
    --argjson chainId "$chain_id" \
    --arg registry "$registry" \
    --arg hook "$hook" \
    --arg rpcUrl "$sanitized_rpc_url" \
    --arg deployer "$deployer" \
    --arg updatedAt "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    '.updatedAt = $updatedAt
    | .[$key] = {
        chainId: $chainId,
        registry: $registry,
        hook: $hook,
        rpcUrl: $rpcUrl,
        deployer: $deployer
      }' \
    "$DEPLOYMENTS_FILE" > "$tmp_file"

  mv "$tmp_file" "$DEPLOYMENTS_FILE"
}

mark_deployment_skipped() {
  local key="$1"
  local chain_id="$2"
  local rpc_url="$3"
  local deployer="$4"
  local reason="$5"
  local sanitized_rpc_url
  local tmp_file
  tmp_file="$(mktemp)"
  sanitized_rpc_url="$(sanitize_rpc_url "$rpc_url")"

  jq \
    --arg key "$key" \
    --argjson chainId "$chain_id" \
    --arg rpcUrl "$sanitized_rpc_url" \
    --arg deployer "$deployer" \
    --arg reason "$reason" \
    --arg updatedAt "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    '.updatedAt = $updatedAt
    | .[$key] = {
        chainId: $chainId,
        skipped: true,
        reason: $reason,
        rpcUrl: $rpcUrl,
        deployer: $deployer
      }' \
    "$DEPLOYMENTS_FILE" > "$tmp_file"

  mv "$tmp_file" "$DEPLOYMENTS_FILE"
}

read_native_balance() {
  local addr="$1"
  local rpc_url="$2"
  local attempt
  local balance

  for attempt in 1 2 3; do
    if balance="$(cast balance "$addr" --rpc-url "$rpc_url" 2>/dev/null)"; then
      echo "$balance"
      return 0
    fi
    sleep 1
  done

  return 1
}

print_runfile_txs() {
  local run_file="$1"
  local explorer_base="$2"
  if [ ! -f "$run_file" ]; then
    echo "[multichain] WARN: missing run file: $run_file"
    return 0
  fi

  jq -r '.transactions[] | .hash // empty' "$run_file" | while IFS= read -r tx_hash; do
    [ -z "$tx_hash" ] && continue
    if [ -n "$explorer_base" ]; then
      echo "  - ${tx_hash}"
      echo "    ${explorer_base}${tx_hash}"
    else
      echo "  - ${tx_hash}"
    fi
  done
}

# Defaults to public RPC endpoints. Override in .env for provider-specific URLs.
BASE_SEPOLIA_RPC_URL="${BASE_SEPOLIA_RPC_URL:-https://sepolia.base.org}"
OPTIMISM_SEPOLIA_RPC_URL="${OPTIMISM_SEPOLIA_RPC_URL:-https://sepolia.optimism.io}"
ARBITRUM_SEPOLIA_RPC_URL="${ARBITRUM_SEPOLIA_RPC_URL:-https://sepolia-rollup.arbitrum.io/rpc}"
POLYGON_RPC_URL="${POLYGON_RPC_URL:-https://polygon-bor-rpc.publicnode.com}"

upsert_env "BASE_SEPOLIA_RPC_URL" "$BASE_SEPOLIA_RPC_URL"
upsert_env "OPTIMISM_SEPOLIA_RPC_URL" "$OPTIMISM_SEPOLIA_RPC_URL"
upsert_env "ARBITRUM_SEPOLIA_RPC_URL" "$ARBITRUM_SEPOLIA_RPC_URL"
upsert_env "POLYGON_RPC_URL" "$POLYGON_RPC_URL"

# Defaults from /context/uniswap_docs/docs/docs/contracts/v4/deployments.mdx.
upsert_env "BASE_SEPOLIA_POOL_MANAGER_ADDRESS" "${BASE_SEPOLIA_POOL_MANAGER_ADDRESS:-0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408}"
upsert_env "BASE_SEPOLIA_POSITION_MANAGER_ADDRESS" "${BASE_SEPOLIA_POSITION_MANAGER_ADDRESS:-0x4b2c77d209d3405f41a037ec6c77f7f5b8e2ca80}"
upsert_env "BASE_SEPOLIA_UNIVERSAL_ROUTER_ADDRESS" "${BASE_SEPOLIA_UNIVERSAL_ROUTER_ADDRESS:-0x492e6456d9528771018deb9e87ef7750ef184104}"

upsert_env "ARBITRUM_SEPOLIA_POOL_MANAGER_ADDRESS" "${ARBITRUM_SEPOLIA_POOL_MANAGER_ADDRESS:-0xFB3e0C6F74eB1a21CC1Da29aeC80D2Dfe6C9a317}"
upsert_env "ARBITRUM_SEPOLIA_POSITION_MANAGER_ADDRESS" "${ARBITRUM_SEPOLIA_POSITION_MANAGER_ADDRESS:-0xAc631556d3d4019C95769033B5E719dD77124BAc}"
upsert_env "ARBITRUM_SEPOLIA_UNIVERSAL_ROUTER_ADDRESS" "${ARBITRUM_SEPOLIA_UNIVERSAL_ROUTER_ADDRESS:-0xefd1d4bd4cf1e86da286bb4cb1b8bced9c10ba47}"

# Polygon mainnet defaults from /context/uniswap_docs/docs/docs/contracts/v4/deployments.mdx.
upsert_env "POLYGON_POOL_MANAGER_ADDRESS" "${POLYGON_POOL_MANAGER_ADDRESS:-0x67366782805870060151383f4BbFF9daB53e5cD6}"
upsert_env "POLYGON_POSITION_MANAGER_ADDRESS" "${POLYGON_POSITION_MANAGER_ADDRESS:-0x1Ec2eBf4F37E7363FDfe3551602425af0B3ceef9}"
upsert_env "POLYGON_UNIVERSAL_ROUTER_ADDRESS" "${POLYGON_UNIVERSAL_ROUTER_ADDRESS:-0x1095692a6237d83c6a72f3f5efedb9a670c49223}"

# Optimism Sepolia v4 infra defaults are not in local context; enable only with explicit addresses.
DEPLOY_OPTIMISM_SEPOLIA="${DEPLOY_OPTIMISM_SEPOLIA:-false}"
upsert_env "DEPLOY_OPTIMISM_SEPOLIA" "$DEPLOY_OPTIMISM_SEPOLIA"

# Polygon deployment is included by default, and auto-skips when deployer has zero MATIC.
DEPLOY_POLYGON="${DEPLOY_POLYGON:-true}"
upsert_env "DEPLOY_POLYGON" "$DEPLOY_POLYGON"

# BaseScript constructor expects these even for pure hook deploy script.
upsert_env "TOKEN0" "${TOKEN0:-0x0000000000000000000000000000000000000001}"
upsert_env "TOKEN1" "${TOKEN1:-0x0000000000000000000000000000000000000002}"

if [ -z "${OWNER_ADDRESS:-}" ] && [ -n "${PRIVATE_KEY:-}" ]; then
  upsert_env "OWNER_ADDRESS" "$(cast wallet address --private-key "$PRIVATE_KEY")"
fi

scripts/bootstrap.sh
ensure_deployments_file

if [ -n "${PRIVATE_KEY:-}" ]; then
  DEPLOYER_ADDRESS="$(cast wallet address --private-key "$PRIVATE_KEY")"
else
  DEPLOYER_ADDRESS="${SENDER:-unknown}"
fi

require_chain_infra() {
  local label="$1"
  local rpc_url="$2"
  local pool_manager_key="$3"
  local position_manager_key="$4"
  local universal_router_key="$5"

  local pool_manager="${!pool_manager_key:-}"
  local position_manager="${!position_manager_key:-}"
  local universal_router="${!universal_router_key:-}"

  if [ -z "$pool_manager" ] || [ -z "$position_manager" ] || [ -z "$universal_router" ]; then
    echo "[multichain] ERROR: missing infra addresses for ${label}" >&2
    echo "[multichain] Required keys: ${pool_manager_key}, ${position_manager_key}, ${universal_router_key}" >&2
    exit 1
  fi

  local pool_manager_status
  if address_has_code "$pool_manager" "$rpc_url"; then
    pool_manager_status=0
  else
    pool_manager_status="$?"
  fi
  case "$pool_manager_status" in
    0) ;;
    1)
      echo "[multichain] ERROR: ${pool_manager_key} has no code on ${label}: ${pool_manager}" >&2
      exit 1
      ;;
    *)
      echo "[multichain] ERROR: unable to read ${pool_manager_key} on ${label} (RPC/network issue)." >&2
      exit 1
      ;;
  esac

  local position_manager_status
  if address_has_code "$position_manager" "$rpc_url"; then
    position_manager_status=0
  else
    position_manager_status="$?"
  fi
  case "$position_manager_status" in
    0) ;;
    1)
      echo "[multichain] ERROR: ${position_manager_key} has no code on ${label}: ${position_manager}" >&2
      exit 1
      ;;
    *)
      echo "[multichain] ERROR: unable to read ${position_manager_key} on ${label} (RPC/network issue)." >&2
      exit 1
      ;;
  esac

  local universal_router_status
  if address_has_code "$universal_router" "$rpc_url"; then
    universal_router_status=0
  else
    universal_router_status="$?"
  fi
  case "$universal_router_status" in
    0) ;;
    1)
      echo "[multichain] ERROR: ${universal_router_key} has no code on ${label}: ${universal_router}" >&2
      exit 1
      ;;
    *)
      echo "[multichain] ERROR: unable to read ${universal_router_key} on ${label} (RPC/network issue)." >&2
      exit 1
      ;;
  esac

  echo "[multichain] Infra:"
  echo "  poolManager=${pool_manager}"
  echo "  positionManager=${position_manager}"
  echo "  universalRouter=${universal_router}"
}

deploy_one_chain() {
  local label="$1"              # BASE_SEPOLIA
  local expected_chain_id="$2"  # 84532
  local rpc_url="$3"
  local json_key="$4"           # baseSepolia
  local env_registry_key="$5"   # BASE_SEPOLIA_REGISTRY
  local env_hook_key="$6"       # BASE_SEPOLIA_HOOK_ADDRESS
  local explorer_base="$7"
  local pool_manager_key="$8"
  local position_manager_key="$9"
  local universal_router_key="${10}"
  local skip_if_zero_balance="${11:-false}"

  echo
  echo "[multichain] === ${label} ==="
  echo "[multichain] rpc: ${rpc_url}"

  local detected_chain_id
  detected_chain_id="$(cast chain-id --rpc-url "$rpc_url")"
  if [ "$detected_chain_id" != "$expected_chain_id" ]; then
    echo "[multichain] ERROR: ${label} expected chain ${expected_chain_id}, got ${detected_chain_id}" >&2
    exit 1
  fi

  require_chain_infra "$label" "$rpc_url" "$pool_manager_key" "$position_manager_key" "$universal_router_key"

  local existing_registry existing_hook
  existing_registry="${!env_registry_key:-}"
  existing_hook="${!env_hook_key:-}"

  if [ -n "$existing_registry" ] && [ -n "$existing_hook" ]; then
    local registry_code_status
    local hook_code_status

    if address_has_code "$existing_registry" "$rpc_url"; then
      registry_code_status=0
    else
      registry_code_status="$?"
    fi

    if address_has_code "$existing_hook" "$rpc_url"; then
      hook_code_status=0
    else
      hook_code_status="$?"
    fi

    if [ "$registry_code_status" -eq 0 ] && [ "$hook_code_status" -eq 0 ]; then
      echo "[multichain] Reusing deployed addresses from .env"
      echo "[multichain] registry=${existing_registry}"
      echo "[multichain] hook=${existing_hook}"

      update_deployments_file "$json_key" "$expected_chain_id" "$existing_registry" "$existing_hook" "$rpc_url" "$DEPLOYER_ADDRESS"
      return 0
    fi

    if [ "$registry_code_status" -eq 2 ] || [ "$hook_code_status" -eq 2 ]; then
      echo "[multichain] ERROR: unable to verify existing deployment code on ${label} (RPC/network issue)." >&2
      exit 1
    fi
  fi

  if is_truthy "$skip_if_zero_balance"; then
    if [ "$DEPLOYER_ADDRESS" = "unknown" ]; then
      echo "[multichain] WARN: cannot pre-check native balance (unknown deployer in account mode)."
    else
      local deployer_balance
      if ! deployer_balance="$(read_native_balance "$DEPLOYER_ADDRESS" "$rpc_url")"; then
        echo "[multichain] ERROR: failed to read deployer balance on ${label}." >&2
        exit 1
      fi

      if [ "$deployer_balance" = "0" ]; then
        echo "[multichain] WARN: skipping ${label}; deployer ${DEPLOYER_ADDRESS} has 0 native gas token."
        mark_deployment_skipped "$json_key" "$expected_chain_id" "$rpc_url" "$DEPLOYER_ADDRESS" "insufficient-native-gas-token"
        return 0
      fi
    fi
  fi

  echo "[multichain] Deploying registry + hook..."
  run_forge_script_broadcast "script/00_DeployHook.s.sol:DeployHookScript" "$rpc_url"

  local run_file="broadcast/00_DeployHook.s.sol/${expected_chain_id}/run-latest.json"
  if [ ! -f "$run_file" ]; then
    echo "[multichain] ERROR: missing run file ${run_file}" >&2
    exit 1
  fi

  local registry_addr hook_addr
  registry_addr="$(jq -r '.transactions[] | select(.contractName == "RoutingPolicyRegistry") | .contractAddress // empty' "$run_file" | tail -n1)"
  hook_addr="$(jq -r '.transactions[] | select(.contractName == "ChainLocalizedRoutingHook") | .contractAddress // empty' "$run_file" | tail -n1)"
  if [ -z "$registry_addr" ] || [ -z "$hook_addr" ]; then
    echo "[multichain] ERROR: unable to parse deployed addresses from ${run_file}" >&2
    exit 1
  fi

  upsert_env "$env_registry_key" "$registry_addr"
  upsert_env "$env_hook_key" "$hook_addr"
  update_deployments_file "$json_key" "$expected_chain_id" "$registry_addr" "$hook_addr" "$rpc_url" "$DEPLOYER_ADDRESS"

  echo "[multichain] registry=${registry_addr}"
  echo "[multichain] hook=${hook_addr}"
  echo "[multichain] txs:"
  print_runfile_txs "$run_file" "$explorer_base"
}

deploy_one_chain \
  "BASE_SEPOLIA" \
  "84532" \
  "$BASE_SEPOLIA_RPC_URL" \
  "baseSepolia" \
  "BASE_SEPOLIA_REGISTRY" \
  "BASE_SEPOLIA_HOOK_ADDRESS" \
  "https://sepolia.basescan.org/tx/" \
  "BASE_SEPOLIA_POOL_MANAGER_ADDRESS" \
  "BASE_SEPOLIA_POSITION_MANAGER_ADDRESS" \
  "BASE_SEPOLIA_UNIVERSAL_ROUTER_ADDRESS"

if is_truthy "$DEPLOY_OPTIMISM_SEPOLIA"; then
  deploy_one_chain \
    "OPTIMISM_SEPOLIA" \
    "11155420" \
    "$OPTIMISM_SEPOLIA_RPC_URL" \
    "optimismSepolia" \
    "OPTIMISM_SEPOLIA_REGISTRY" \
    "OPTIMISM_SEPOLIA_HOOK_ADDRESS" \
    "https://sepolia-optimism.etherscan.io/tx/" \
    "OPTIMISM_SEPOLIA_POOL_MANAGER_ADDRESS" \
    "OPTIMISM_SEPOLIA_POSITION_MANAGER_ADDRESS" \
    "OPTIMISM_SEPOLIA_UNIVERSAL_ROUTER_ADDRESS"
else
  echo
  echo "[multichain] === OPTIMISM_SEPOLIA ==="
  echo "[multichain] Skipping by default (DEPLOY_OPTIMISM_SEPOLIA=false)."
  echo "[multichain] To enable, set DEPLOY_OPTIMISM_SEPOLIA=true and define:"
  echo "  OPTIMISM_SEPOLIA_POOL_MANAGER_ADDRESS"
  echo "  OPTIMISM_SEPOLIA_POSITION_MANAGER_ADDRESS"
  echo "  OPTIMISM_SEPOLIA_UNIVERSAL_ROUTER_ADDRESS"
fi

deploy_one_chain \
  "ARBITRUM_SEPOLIA" \
  "421614" \
  "$ARBITRUM_SEPOLIA_RPC_URL" \
  "arbitrumSepolia" \
  "ARBITRUM_SEPOLIA_REGISTRY" \
  "ARBITRUM_SEPOLIA_HOOK_ADDRESS" \
  "https://sepolia.arbiscan.io/tx/" \
  "ARBITRUM_SEPOLIA_POOL_MANAGER_ADDRESS" \
  "ARBITRUM_SEPOLIA_POSITION_MANAGER_ADDRESS" \
  "ARBITRUM_SEPOLIA_UNIVERSAL_ROUTER_ADDRESS"

if is_truthy "$DEPLOY_POLYGON"; then
  deploy_one_chain \
    "POLYGON" \
    "137" \
    "$POLYGON_RPC_URL" \
    "polygon" \
    "POLYGON_REGISTRY" \
    "POLYGON_HOOK_ADDRESS" \
    "https://polygonscan.com/tx/" \
    "POLYGON_POOL_MANAGER_ADDRESS" \
    "POLYGON_POSITION_MANAGER_ADDRESS" \
    "POLYGON_UNIVERSAL_ROUTER_ADDRESS" \
    "true"
else
  echo
  echo "[multichain] === POLYGON ==="
  echo "[multichain] Skipping (DEPLOY_POLYGON=false)."
fi

echo
echo "[multichain] Completed multi-chain deployment pipeline."
echo "[multichain] Updated .env keys:"
echo "  BASE_SEPOLIA_REGISTRY, BASE_SEPOLIA_HOOK_ADDRESS"
echo "  OPTIMISM_SEPOLIA_REGISTRY, OPTIMISM_SEPOLIA_HOOK_ADDRESS (if enabled)"
echo "  ARBITRUM_SEPOLIA_REGISTRY, ARBITRUM_SEPOLIA_HOOK_ADDRESS"
echo "  POLYGON_REGISTRY, POLYGON_HOOK_ADDRESS (if enabled and funded)"
echo "[multichain] Deployment registry file: ${DEPLOYMENTS_FILE}"
